---
# tasks file for http

- name: Install nginx
  ansible.builtin.package:
    name: 'nginx'
    state: present

#enabled service nginx
- name: "Enable service nginx"
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started
