---
# tasks file for php

- name: Install php-fpm
  become: true
  ansible.builtin.package:
    name: 'php-fpm'
    state: present

#enabled service php-fpm
- name: "Enable service php-fpm"
  ansible.builtin.service:
    name: php-fpm
    enabled: yes
    state: started

# Копируем страницу с выводом PHP версии
- name: Copy index.php 
  ansible.builtin.copy:
    src: index.php 
    dest: /usr/share/nginx/html/ # link to /path/to/file
    follow: yes

# меняем прослушивание php-fpm с сокета на tcp файл www.conf
# ;listen = /run/php-fpm/www.sock
# listen = 127.0.0.1:9000
# копируем измененный конфиг

# Удаляем старый настроечный файл
- name: Delete file www.conf
  ansible.builtin.file:
    state: absent
    path: /etc/php-fpm.d/www.conf

# Копируем конфигурационный файл www.conf
- name: Copy php.conf 
  ansible.builtin.copy:
    src: www.conf
    dest: /etc/php-fpm.d/
    follow: yes

# Удаляем старый настроечный файл
- name: Delete file php.conf
  ansible.builtin.file:
    state: absent
    path: /etc/nginx/default.d/php.conf

# Копируем конфигурационный файл php.conf
- name: Copy php.conf 
  ansible.builtin.copy:
    src: php.conf 
    dest: /etc/nginx/default.d/ # link to /path/to/file
    follow: yes  

  notify:
    - Restart php-fpm
    - Restart nginx